# Generated by Django 4.1.7 on 2023-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
