# Generated by Django 4.1.7 on 2023-04-06 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
