# Generated by Django 4.1.7 on 2023-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_quantity_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(default='нет автора', max_length=100),
        ),
    ]
