# Generated by Django 4.1.7 on 2023-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_name',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='нет автора', max_length=100),
        ),
    ]
