# Generated by Django 4.1.7 on 2023-04-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='нет автора', max_length=100),
        ),
    ]
